"""add pickup otp hash

Revision ID: 40e176cb9960
Revises: ff635aad689a
Create Date: 2026-09-20 20:06:35.669479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e176cb9960'
down_revision: Union[str, Sequence[str], None] = 'ff635aad689a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surplus_listing', sa.Column('pickup_otp_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surplus_listing', 'pickup_otp_hash')
    # ### end Alembic commands ###
