"""add compliance record table

Revision ID: b0f4250bf325
Revises: 40e176cb9960
Create Date: 2026-09-21 09:08:13.656808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f4250bf325'
down_revision: Union[str, Sequence[str], None] = '40e176cb9960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('donor_org_id', sa.Integer(), nullable=False),
    sa.Column('recipient_org_id', sa.Integer(), nullable=False),
    sa.Column('food_item', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['surplus_listing.id'], ),
    sa.ForeignKeyConstraint(['recipient_org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_record')
    # ### end Alembic commands ###
