"""add accepted_by_org_id to surplus listing

Revision ID: ff635aad689a
Revises: c90d6b976b83
Create Date: 2026-09-20 20:04:23.345831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff635aad689a'
down_revision: Union[str, Sequence[str], None] = 'c90d6b976b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surplus_listing', sa.Column('accepted_by_org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surplus_listing', 'organisation', ['accepted_by_org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'surplus_listing', type_='foreignkey')
    op.drop_column('surplus_listing', 'accepted_by_org_id')
    # ### end Alembic commands ###
